services:
  - type: web
    name: waterfull
    env: node
    branch: main
    plan: free
    buildCommand: apt-get update && apt-get install -y fonts-noto-cjk && npm install
    startCommand: npm start
    autoDeploy: true
